name: Deploy to Production

on:
  push:
    branches:
      - release  # Only trigger on push to release branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Execute SSH Command
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            sudo su - 
            set -x 
            cd /opt/learngeeta/olympiad
            git status
            git checkout release
            git pull --rebase
            git status
            # Add any additional deployment commands here
            ./setup.sh
            docker compose down -v
            docker compose up -d 
            sleep 5 
            docker compose logs